version: '3'
services:
  db:
    image: postgres
    container_name: tetpostgres_db
    env_file:
      - .db.env
    ports:
      - "5432:5432"
  app:
    image: tetproject:latest
    entrypoint:
      - bash
      - entrypoint.sh
    build: .
    container_name: tetpostgres_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/tetproject
    env_file:
       - .app.env
    links:
      - db
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    # command: puma
